concat: false
connectivity_input: 10
connectivity_inter: 10
connectivity_recurrent: 10
input_scaling: 1
inter_scaling: 1
layers: 1
leaky: 1.0
radius: 0.1
return_sequences: false
units: 550
validation_loss: 0.00010144213592866436
