concat: false
connectivity_input: 10
connectivity_inter: 10
connectivity_recurrent: 10
input_scaling: 1
inter_scaling: 1
layers: 1
leaky: 0.67
radius: 0.24
return_sequences: false
units: 850
validation_loss: 0.027808668091893196
