concat: false
connectivity_input: 10
connectivity_inter: 10
connectivity_recurrent: 10
input_scaling: 1
inter_scaling: 1
layers: 1
leaky: 0.53
radius: 0.19
return_sequences: false
units: 450
validation_loss: 3.610119847508031e-06
