concat: false
connectivity_input: 10
connectivity_inter: 10
connectivity_recurrent: 10
input_scaling: 1
inter_scaling: 1
layers: 1
leaky: 0.62
radius: 0.57
return_sequences: false
units: 650
validation_loss: 0.22236940264701843
