concat: false
connectivity_input: 10
connectivity_inter: 10
connectivity_recurrent: 10
input_scaling: 1
inter_scaling: 1
layers: 1
leaky: 0.72
radius: 0.34
return_sequences: false
units: 950
validation_loss: 0.0008658609003759921
