concat: false
connectivity_input: 10
connectivity_inter: 10
connectivity_recurrent: 10
input_scaling: 1
inter_scaling: 1
layers: 1
leaky: 0.48
radius: 0.1
return_sequences: false
units: 150
validation_loss: 0.15936948359012604
