concat: false
connectivity_input: 10
connectivity_inter: 10
connectivity_recurrent: 10
input_scaling: 1
inter_scaling: 1
layers: 1
leaky: 0.34
radius: 0.1
return_sequences: false
units: 950
validation_loss: 5.1780560170300305e-05
