concat: false
connectivity_input: 10
connectivity_inter: 10
connectivity_recurrent: 10
input_scaling: 1
inter_scaling: 1
layers: 1
leaky: 0.86
radius: 1.0
return_sequences: false
units: 750
validation_loss: 0.006120560225099325
