concat: false
connectivity_input: 10
connectivity_inter: 10
connectivity_recurrent: 10
input_scaling: 1.0
inter_scaling: 1
layers: 1
leaky: 0.7999999999999999
radius: 0.25
return_sequences: false
units: 700
validation_loss: 0.0015163776697590947
