concat: false
connectivity_input: 10
connectivity_inter: 10
connectivity_recurrent: 10
input_scaling: 1.0
inter_scaling: 1
layers: 1
leaky: 0.7
radius: 0.35
return_sequences: false
units: 675
validation_loss: 0.001965281320735812
