concat: true
connectivity_input: 10
connectivity_inter: 10
connectivity_recurrent: 10
input_scaling: 0.25
inter_scaling: 1.0
layers: 2
leaky: 0.5
radius: 0.6499999999999999
return_sequences: false
units: 675
validation_loss: 0.26164573431015015
